hyprwm/contrib

flake.nix
grimblast/.gitignore
grimblast/Makefile
grimblast/default.nix
grimblast/grimblast
grimblast/grimblast.1.scd

Heyo!
This PR adds grimblast, a screenshot tool based on grimshot.
I've also included a manpage (scdoc format), a Makefile for easily building the docs (and possibly more things such as completions futurely) and installing them to the right places.
There's also a nix derivation for it, that uses the Makefile. The derivation wrapper has hyprland as an input. As we don't want to add hyprland as a flake input here, it defaults to null (which mostly works when hyprctl is on the PATH) when consuming through the flake package/overlay, and can be overridden.
I can write a PKGBUILD too, but I don't plan on maintaining an AUR package.

add grimblast

---

grimblast/grimblast

Fixes #3
This is the simplest approach I could think of. Specifying both `copy` and `save` in one command would've required a better parsing mechanism that I honestly don't know how to implement in bash.
Feel free to suggest a better approach.

grimblast: add copysave option

---

grimblast/default.nix

Bumping nixpkgs caused an error related to grimblasts' meta:
```
->> home-manager --flake . switch 
error: Package ‘grimblast-0.1’ in /nix/store/331y7r22jc0pdlki8axnzgby1mipdc4b-source/grimblast/default.nix:38 has an invalid meta attrset:
- key 'meta.maintainer' is unrecognized; expected one of:
['available', 'badPlatforms', 'branch', 'broken', 'changelog', 'description', 'downloadPage', 'executables', 'homepage', 'hydraPlatforms', 'insecure', 'isBuildPythonPackage', 'isFcitxEngine', 'isGutenprint', 'isIbusEngine', 'knownVulnerabilities', 'license', 'longDescription', 'mainProgram', 'maintainers', 'maxSilent', 'name', 'outputsToInstall', 'platforms', 'position', 'priority', 'schedulingPriority', 'sourceProvenance', 'tag', 'tests', 'timeout', 'unfree', 'unsupported', 'version'], refusing …
```

grimblast/nix: fix meta.maintainers key

---

grimblast/grimblast

quoting the $REST argument was causing notify to treat the arguments as a single token instead of the multiple tokens required for the notify icon to be set correctly.

grimblast: fix parameter quoting in notifyOk

---

grimblast/grimblast

You can now use `grimblast area` instead of using `grimblast window`. The functionality is combined, thus there's no need to keep them separate.
Fixes #21 
Feel free to approve/comment on this PR.

grimblast: merge window into area

---

grimblast/grimblast
grimblast/screenshot.sh

There were some issues in the GRIMBLAST_EDITOR check function.
no matter if the variable is in env or not it is used to use gimp.
Fixed that.
and made notifications to show image previews if possible.
now users can use `GRIMBLAST_EDITOR="swappy -f"`

Fixed GRIMBLAST Variable check and fix formatting

---

.github/workflows/check.yml
flake.nix
hyprprop/.gitignore
hyprprop/Makefile
hyprprop/default.nix
hyprprop/hyprprop
hyprprop/hyprprop.1.scd

Adds hyprprop, a xprop replacement for hyprland, it allows you to select a window to view its properties from hyprctl.
Useful for getting information for window rules and checking if things are using xwayland.

Add hyprprop

---

hyprprop/default.nix

With this PR, you can run hyprprop inside a terminal from a launcher like `fuzzel`.
An example configuration is as follows:
```sh
bind = $mod, Space, exec, fuzzel -T "footclient -H"
```

hyprprop: Add a desktop item

---

.github/workflows/check.yml
README.md
flake.nix
try_swap_workspace/Makefile
try_swap_workspace/default.nix
try_swap_workspace/try_swap_workspace

Hey :wave: 
Inspired from [this discussion on the hyprland repository](https://github.com/hyprwm/Hyprland/discussions/835) try_swap_workspace is a binding to mimic the 'arbitrary workspace on arbitrary monitor' on arbitrary monitor behavior known from may window managers.
This means:
- if a workspace is not displayed on any monitor and should be displayed, it gets displayed on the currently focused monitor
- if a workspace is already displayed on another monitor and should displayed on the currently focused monitor, the displayed workspace on the focused monitor will be swapped with the workspace on the monitor that should be displayed on the focused monitor
I hope this helps some people that want hyprland to behave like their old windowmanager. (For me that was xmonad). I tried to mimic …

add feature try_switch_workspace

---

grimblast/grimblast

Fixes #37
Adds `-f | --freeze` flag (only works in `area` mode). This freezes the screen using `hyprpicker -r -z` so make sure you have that installed. As always, `grimblast check` tells you whether you're missing anything.

grimblast: add --freeze argument

---

scratchpad/scratchpad

* Rofi shows "scratchpad" as title instead of "dmenu".
* If menu is running already, don't try to run it again.

feat(scratchpad): Minor improvements

---

grimblast/grimblast

Fixes #50
`--freeze` currently does not work as expected - the screenshot is taken after the `hyprpicker` process is killed and the resulting screenshot is not of the "frozen" screen. The solution is to delay killing hyprpicker until after the screenshot has been taken.

Fix grimblast freeze

---

scratchpad/scratchpad

This commit fixes window is hidden behind the floating windows when reterivied from the scratchpad
Also formatts the code with shfmt

Fixes window get's hidden behind other windows when called back.

---

hdrop/default.nix

```
error: attribute 'agpl' missing
at /nix/store/blnk3ibcrb52nj2wvcn6any566h1j5aj-source/hdrop/default.nix:36:15:
35|     description = "Emulate 'tdrop' in Hyprland (show and hide specific programs per keybind)";
36|     license = licenses.agpl;
|               ^
37|     platforms = platforms.unix;
Did you mean one of agpl3, eapl, gfl, gpl2 or gpl3?
```
https://github.com/Schweber/hdrop/blob/main/LICENSE

fix: hdrop valid license

---

scratchpad/scratchpad

Now sending window to scratchpad will not switch to scratchpad workspace

Changed `movetoworkspace` to `movetoworkspacesilent`

---

scratchpad/scratchpad

May resolve #76
Introduced a feature that allows the user to set the name of the scratchpad.
Changed formatting from spaces to tabs (`shfmt` to be blamed)

Added feature to choose scratchpad name

---

hdrop/Makefile

This simply fix the hdrop Makefile of when running `make install`
To be consistent with the other application Makefiles

hdrop: fix make install in Makefile

---

CHANGELOG.md
grimblast/grimblast
grimblast/grimblast.1.scd

`grimblast` now respects `$SLURP_ARGS`, which controls how `slurp` looks and
behaves. See `slurp -h` for options.
Fixes #83.
maintainer
it)
- For changes

grimblast: allow customizing slurp

---

CHANGELOG.md
grimblast/grimblast

Despite disabling `fade` and `fadeOut`, border is visible sometimes when capturing area cause fades are being restored abit early 
maintainer
it)
- For changes

grimblast: reset fade after calling grim

---

CHANGELOG.md
grimblast/grimblast

Save the screenshot to a file in the `/tmp/` folder when using `copy` to show it on the notification.
maintainer
it)
- For changes

grimblast: show screenshot on 'copy' notification

---

grimblast/grimblast

Fixed an issue with my last commit, the screenshot was showing on the notification but it wasn't saved to the buffer, I double checked and this version now works as intended. I'm using the same tactic with `tee` used to show the screenshot when using `copysave`
maintainer
it)
- For changes

grimblast: fixed image not going to buffer

---

CHANGELOG.md
scratchpad/scratchpad

Allows supplying arguments like `-g` first instead of last to scratchpad:
```
./scratchpad -g -m 'wofi --show dmenu -i' -l
```
Also specify that `-l` needs to be used in addition to `-g`.
maintainer
it)
- For changes

scratchpad: allow supplying command flags in any order

---

CHANGELOG.md
grimblast/grimblast

seems now it depends only on `fadeLayers`, which has `0` speed by default, but when set to higher values borders are visible again

grimblast: respect fadeLayers

---

CHANGELOG.md
flake.lock
grimblast/default.nix

make hyprpicker available to grimblast. I had to update the flake since it wasn't packaged yet on the lock's version.
However, there is a current issue with `nixpkgs`'s hyprpicker: https://github.com/hyprwm/hyprpicker/issues/51 and a workaround is presented in the issue tracker
maintainer
it)
- For changes

grimblast: include `hyprpicker` to closure

---

CHANGELOG.md
scratchpad/default.nix

Ran into an issue where scratchpad couldn't find awk when being ran from KDE Connect.
maintainer
it)
- For changes

scratchpad: add gawk to closure

---

CHANGELOG.md
hdrop/default.nix

The `agpl3` license was split into `agpl3Only` and `agpl3Plus` in nixpkgs, and `agpl3` was removed. I've updated it to `agpl3Only`. See NixOS/nixpkgs#297173.
maintainer
it)
- For changes

hdrop: fix Nix meta.license value

---

CHANGELOG.md
shellevents/README.md
shellevents/shellevents

I have written a README.md for `shellevents`. It was such an awesome tool but the lack of a README.md deterred me from trying. It was only until now did I realize its power and hence the README.md. Thank you!
- For changes

docs: write README.md

---

CHANGELOG.md
grimblast/grimblast

Changed the line responsible for getting workspace ids to include special workspaces and ignore the active workspace if a special one is above it. Without it, it was not possible to make a screenshot of a window which is on a special workspace (`grimblast copy area`).
maintainer
it)
- For changes

grimblast: recognize windows of special workspaces

---

CHANGELOG.md
grimblast/grimblast

grimblast:  only allow one instance (modified)

---

CHANGELOG.md
grimblast/grimblast
grimblast/grimblast.1.scd

Allow only one instance of grimblast to be active at a time. Fixes #112
maintainer
it)
- For changes

grimblast: only allow one instance

---

CHANGELOG.md
grimblast/grimblast

Fixes window selection on fullscreen windows by filtering only the windows with fullscreen when on fullscreen active workspaces. 
- For changes

grimblast: fix window area selection on fullscreen workspaces

---

CHANGELOG.md
grimblast/grimblast
grimblast/grimblast.1.scd

`grimblast --wait` currently only allows whole numbers, and I myself like to use it to get the cursor out of the way for screenshots, however a whole second is just a bit too unnatural too long for me and I'd like to use something like 0.5 or 0.7, so I've changed the regex to allow adding decimal numbers (I hope the regex is alright)
The usage still says `[--wait N]` but I initally expected `N` to also include decimal numbers, so not sure if this should just stay the same or if the usage should also mention that decimals are allowed, although I think that may be a bit confusing and should just stay this way
maintainer
it)
- For changes

grimblast: allow decimals for --wait

---

CHANGELOG.md
grimblast/grimblast
grimblast/grimblast.1.scd

Allow Opening File Folder When Clicking Notification

---

CHANGELOG.md
grimblast/grimblast
grimblast/grimblast.1.scd

fixes #134
The grim cursor is not visible by default, but if your machine has high CPU loads you can add `env = GRIMBLAST_HIDE_CURSOR, 0` to your Hyprland config file (the grim cursor will be visible).
- For changes

grimblast: add environment var 'GRIMBLAST_HIDE_CURSOR' to avoid high CPU loads on some machines

---

CHANGELOG.md
grimblast/grimblast

Avoids confusions like these https://github.com/hyprwm/contrib/issues/47 by making sure the tool can only run in hyprland (found my own issue while having the same problem but just forgot lmao)
(or i could try making it work in sway but i don't know if the goal is to make these tools for hyprland specifically or not)

grimblast: checks if grimblast is running in hyprland

---

CHANGELOG.md
grimblast/grimblast

This PR fixes https://github.com/hyprwm/contrib/issues/137.
- `takeScreenshot() {…}` has been tweaked to use proper `if` statements, fixing a common "A && B || C" problem that made an error notification appear in certain circumstances where there should be none.
- `HYPRPICKER_PID` has been removed thanks to a re-write of `killHyprpicker() {…}` by @DHDcc.
- Currently line 28 is now `trap 'rm -f "$grimblastInstanceCheck"' EXIT`, fixing a simple syntax issue that, whilst not affecting functionality, was still technically wrong.
- If empty spaces at the end of some lines were removed, this was done automatically by my text editor; I guess a little cleaning is still a nice bonus.
- The changelog was updated to add these changes.
- @DHDcc 
- Myself
- @fufexan

Fix erroneous error message when taking screenshots under certain circumstances.

---

CHANGELOG.md
grimblast/grimblast

Removed `moveCursorPosition` and `restoreCursorPosition` functions for `OUTPUT` as they are only needed for an area screenshot and removed a duplicate `jq` command to avoid redundancy.
- For changes

grimblast: remove `moveCursorPosition` and `restoreCursorPosition` for `OUTPUT` and duplicate `jq` command

---

CHANGELOG.md
grimblast/grimblast

Use `--batch` for `hyprctl` to limit the number of control calls.
- For changes

grimblast: use `--batch` for `hyprctl` to limit the number of control calls

---

CHANGELOG.md
hdrop/README.md
hdrop/hdrop

Update hdrop to its latest version. This is needed to make it compatible with Hyprland v0.48 or higher.
- For changes

hdrop: 0.7.6 -> 0.7.7

---

CHANGELOG.md
grimblast/grimblast

Previously, at least for me, using `--openfile` with `grimblast` would always fail. This fix corrects the file URI used when opening a file from a notification. Refer to the video attached.
https://github.com/user-attachments/assets/f9250d08-b5ec-415d-bef1-048a6ec02e6b
- For changes

grimblast: fix file URI when using --openfile

---

CHANGELOG.md
try_swap_workspace/try_swap_workspace

When coming out of standby, the order of `hyprctl monitors` can change. This led try_swap_workspace to target the wrong monitor.
Using the json output ties the ID to the relevant data.
- For changes

try_swap_workspace: fix monitor ID after standby

---

CHANGELOG.md
grimblast/grimblast

The `trap cleanup EXIT` was placed before the `GRIMBLASTLOCK` check, causing the lock file to be deleted on exit. As a result, the program would start again on the next invocation.
- For changes

bug: Fix a bug where grimblast would delete the lock file when early exiting
