hyprwm/contrib

- grimblast/grimblast
Updated Output selection with new Focused syntax
> Updated Output selection syntax

- grimblast/grimblast
> Feat: Limit copy window to only selection

- grimblast/grimblast
Fixed a quoting error in previous PR.
> Quoting Error

- grimblast/grimblast
When using window mode in fullscreen, you will still have the selection "window" stuff, when you really shouldn't.
Let me know whether when in fullscreen, should you just copy screen, or select region(area)
> Fix: window mode in fullscreen

- grimblast/grimblast
Corrected output matching error
> Matching error

- grimblast/grimblast
> Revert "Fix: window mode in fullscreen"

- .github/workflows/check.yml
- README.md
- grimblast/grimblast
- grimblast/grimblast.1.scd
- grimblast/screenshot.sh
Add edit option to grimblast and copy of my rofi screenshot applet script you can see both in action on this video:
https://raw.githubusercontent.com/MrDuartePT/contrib/main/grimblast/preview%20grimblast%20features.mp4
> add edit option and rofi screenshot applet

- scratchpad/scratchpad
now command arguments should work.
@fufexan This should evaluate commands arguments in `-m`
> Fixed `-m` command args

- scratchpad/scratchpad
> HOTFIX for non `-m` users

- .github/workflows/check.yml
- CHANGELOG.md
- README.md
Easier to add scripts to CI. Separate changelog file.
> Better organize the repo

- grimblast/grimblast
- grimblast/grimblast.1.scd
Fixes #57.
Inspired by https://github.com/OctopusET/sway-contrib/commit/695c70deab5279b61df8ec9420030c133599253a.
> grimblast: implement --wait

- shellevents/shellevents
- shellevents/shellevents_default.sh
Add support for `activewindowv2` and `windowtitle` events.
> shellevents: support more events

- README.md
- hdrop/README.md
- hdrop/default.nix
- hdrop/hdrop
- hdrop/hdrop.1.scd
Changed `hyprwm/contrib` README description of hdrop
added --insensitive and --verbose
Improved documentation.
> hdrop: 0.2.4 -> 0.3.0

- CHANGELOG.md
- hdrop/Makefile
- hdrop/README.md
- hdrop/default.nix
- hdrop/hdrop
- hdrop/hdrop.1.scd
> hdrop: 0.3.0 -> 0.4.0

- CHANGELOG.md
- hdrop/default.nix
- hdrop/hdrop
> hdrop: 0.4.2 -> 0.4.4

- CHANGELOG.md
- hdrop/README.md
- hdrop/default.nix
- hdrop/hdrop
- hdrop/hdrop.1.scd
add hdrop to Changelog
maintainer
it)
- For changes
> hdrop: 0.4.4 -> 0.5.0

- CHANGELOG.md
- scratchpad/scratchpad
Switched to `spaces` from `tabs`
And removed `exit` from `pgrep` as sometimes it used to exit the script even before showing the menu.
> Fixed -m command.

- shellevents/shellevents
- shellevents/shellevents_default.sh
add missing shell events from https://wiki.hyprland.org/IPC/#tmphyprhissocket2sock
Also, replace `readlink -mn` with `realpath` cause realpath is doing the same and `readlink -m` option is not compatible with busybox
> actualize shellevents

- CHANGELOG.md
- hdrop/README.md
- hdrop/default.nix
- hdrop/hdrop
- hdrop/hdrop.1.scd
https://github.com/Schweber/hdrop/releases
sorted inputs alphabetically in default.nix
formatted with the new nixpkgs-fmt
maintainer
it)
- For changes
> hdrop: 0.5.0 -> 0.5.3

- CHANGELOG.md
- hdrop/README.md
- hdrop/default.nix
- hdrop/hdrop
- hdrop/hdrop.1.scd
https://github.com/Schweber/hdrop/releases
maintainer
it)
- For changes
> hdrop: 0.5.3 -> 0.6.0

- CHANGELOG.md
- shellevents/shellevents
- shellevents/shellevents_default.sh
> shellevents: add windowtitlev2 event

- CHANGELOG.md
- grimblast/grimblast
> grimblast: hide the grim cursor before taking a screenshot

- CHANGELOG.md
- hdrop/README.md
- hdrop/default.nix
- hdrop/hdrop
- hdrop/hdrop.1.scd
Update hdrop to its latest version, currently 0.7.6.
- For changes
> hdrop: 0.6.0 -> 0.7.6

- CHANGELOG.md
- shellevents/shellevents
- shellevents/shellevents_default.sh
Following https://github.com/hyprwm/Hyprland/commit/79b526a04199a05d1e9b0bbb035ba20b652a7a2b
- For changes
> shellevents: support minimized event

- CHANGELOG.md
- grimblast/grimblast
- grimblast/grimblast.1.scd
Originally implemented to fix https://github.com/hyprwm/contrib/issues/115, caused more trouble than it solved.
See #157, #155, #154, #143, etc.
@vaxerski
- For changes
> grimblast: nuke cursor position shenanigans

- CHANGELOG.md
- grimblast/grimblast
Now allows arguments and options to be mixed.
@vaxerski
- For changes
> grimblast: rework options and arguments parsing

- CHANGELOG.md
- grimblast/screenshot.sh
Refactor screenshot menu script
- Add Wofi/Rofi/Walker detection and menu support
- Simplify timer notifications and unify menu functions
- Convert option lists to arrays and fix Bash syntax issues
- For changes
> grimblast : add support for screenshot menu script
